console.log("     /~\\");
console.log("    ( oo|");
console.log("    _\\=/_");
console.log("   /  _  \\");
console.log("  //|/.\\|\\\\");
console.log(" ||  \\ /  ||");
console.log("============");
console.log("|          |");
console.log("|          |");
console.log("|          |");
